const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST"

const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS"

const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE"

const BOOK_ADD_CART = "BOOK_ADD_CART"

const BOOK_REMOVE_CART = "BOOK_REMOVE_CART"

const ALL_BOOKS_REMOVE_CART = "ALL_BOOKS_REMOVE_CART"

export {
  FETCH_BOOKS_REQUEST,
  FETCH_BOOKS_SUCCESS,
  FETCH_BOOKS_FAILURE,
  BOOK_ADD_CART,
  BOOK_REMOVE_CART,
  ALL_BOOKS_REMOVE_CART
}
