const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST"

const FETCH_BOOKS_SUCCESS  = "FETCH_BOOKS_SUCCESS"

const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE"

const BOOK_ADD_CART = "BOOK_ADD_CART"

export { FETCH_BOOKS_REQUEST, FETCH_BOOKS_SUCCESS, FETCH_BOOKS_FAILURE, BOOK_ADD_CART }
